# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2b4cb35f2d9b1542e0774b47f2993ea822c55886b30b49f1f3ccabc937836a1766cdd4d232fae016ba63219d70de177a29ea1accf89e6ee755a5ef5fb53c5a0

test:
  secret_key_base: 8f932cc5de5a2d93ef5df8c2173305e653b323808d6ee6fb17d5db53ea8ef30a1d5750e98950f8a8d69a6f28c60bd10aa7f0a0e12bbd17468780fcc34518b30d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
